version: "3"

tasks:
  check:
    cmds:
      - trunk check -a
  pre-commit:
    cmds:
      - trunk check --ci
  tidy:
    desc: Run "go mod tidy -go=1.8" in all packages
    cmds:
      - find . -name 'go.mod' -print0 | xargs -0 -I {} /bin/bash -c 'pushd `dirname $1`; go mod tidy -go=1.18; popd' '_' '{}' \+
  update:
    desc: Run "go get -u ./..." in all packages
    cmds:
      - find . -name 'go.mod' -print0 | xargs -0 -I {} /bin/bash -c 'pushd `dirname $1`; go get -u ./...; popd' '_' '{}' \+
  test:
    desc: Run "go test ./..." in all packages
    cmds:
      - find . -name 'go.mod' -print0 | xargs -0 -I {} /bin/bash -c 'pushd `dirname $1`; go test ./...; popd' '_' '{}' \+
  release:
    desc: "Release a plugin, usage: task release -- broker/http"
    cmds:
      - ./scripts/release.sh {{.CLI_ARGS}}
    preconditions:
      - test -n "{{.CLI_ARGS}}"
  releaseall:
    desc: "Release all packages, will only release changed packages"
    cmds:
      - find . -name 'go.mod' -printf "%h\n" | sort -u | cut -c 3- | xargs -I {} ./scripts/release.sh {} | bash
      - git fetch
