version: "3"

dotenv: [".env"]

tasks:
  check:
    cmds:
      - trunk check -a
  pre-commit:
    cmds:
      - trunk check --ci
  tidy:
    desc: Run "go mod tidy -go=1.8" in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go mod tidy -go=1.18; popd' '_' {} \;
  update:
    desc: Run "go get -u ./..." in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go get -u ./...; popd' '_' {} \;
  test:
    desc: Run "go test ./..." in all packages
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'pushd `dirname $1`; go test ./...; popd' '_' {} \;
  workuse:
    desc: Add all plugins to go.work
    cmds:
      - go work init . || exit 0
      - go work use $(find . -name 'go.mod' -printf "%h\n")
  release:
    desc: "Release a plugin, usage: task release -- broker/http"
    cmds:
      - ./scripts/release.sh {{.CLI_ARGS}}
    preconditions:
      - test -n "{{.CLI_ARGS}}"
  releaseall:
    desc: "Release all packages, will only release changed packages"
    cmds:
      - find . -name 'go.mod' -printf "%h\n" | sort -u | cut -c 3- | xargs -I {} ./scripts/release.sh {} | bash
      - git fetch
  updatev0:
    desc: "Update all v0 in all packages, usage: task updatev0 -- v0.0.5"
    cmds:
      - find . -name 'go.mod' -exec /bin/bash -c 'path=$(dirname $1); pushd $path; go get -u github.com/go-micro/microwire-plugins@{{.CLI_ARGS}}; popd;' '_' {} \;
      - task: tidy
    preconditions:
      - test -n "{{.CLI_ARGS}}"

  builder:
    desc: Run something in the builder container for example "task builder -- go get -u ./..."
    cmds:
      - podman run --rm
        -v "{{.PWD}}:/code"
        -v "{{.GO_VOLUME_PATH}}:/go:rw"
        {{.DOCKER_ORG_JO_MICRO}}/builder:latest {{.CLI_ARGS}}
    vars:
      GO_VOLUME_PATH:
        sh: podman volume inspect microwire_go --format "{{"{{"}}.Mountpoint{{"}}"}}"
    preconditions:
      - test -n "{{.CLI_ARGS}}"

  protoc:
    desc: Generate protobuf go files
    cmds:
      - podman volume inspect microwire_go 1>/dev/null 2>&1 || podman volume create microwire_go
      - task: builder
        vars:
          CLI_ARGS: /scripts/protoc_gen.sh
      - find . -name '*.pb.micro.go' -exec sed -i 's#go-micro.dev/v4#github.com/go-micro/microwire/v5#g' {} \;